# Generated by Django 2.2.5 on 2021-09-22 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='应用系统')),
                ('app_manager', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='系统管理员')),
                ('manager_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='系统管理员电话')),
                ('owner_cop', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='建设单位')),
                ('owner_manager', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='业务管理员')),
                ('owner_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='业务管理员电话')),
                ('describe', models.TextField(blank=True, max_length=128, null=True, verbose_name='系统用途')),
                ('comment', models.TextField(blank=True, default='', max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '所属系统',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='区域')),
                ('subnet', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='IP地址段')),
                ('describe', models.TextField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '所属区域',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='供应商')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='制造商')),
                ('contact', models.CharField(blank=True, max_length=16, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('describe', models.TextField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '供应商信息',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='主机名')),
                ('asset_num', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='资产编号')),
                ('ip_add', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='IP地址')),
                ('mgt_ip_add', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='MGT地址')),
                ('mac_add', models.CharField(default='', max_length=48, verbose_name='MAC地址')),
                ('sn', models.CharField(default='', max_length=128, verbose_name='序列号')),
                ('asset_model', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='型号')),
                ('asset_type', models.CharField(choices=[('cloud_host', '云主机'), ('virtual_machine', '虚拟机'), ('virtual_node', '虚拟宿主机'), ('container_node', '容器主机节点'), ('server', '物理机'), ('switch', '交换机'), ('route', '路由器'), ('firewall', '防火墙'), ('ips', '入侵防御设备'), ('lb', '负载均衡设备'), ('waf', '应用防火墙'), ('pc', '桌面电脑'), ('laptop', '笔记本电脑'), ('printer', '网络打印机'), ('app', '应用系统'), ('database', '数据库'), ('middleware', '中间件'), ('datastore', '存储设备'), ('san_switch', '光纤交换机'), ('byod', '智能终端'), ('other', '其它')], default='pc', max_length=64, verbose_name='资产类型')),
                ('asset_criticality_choice', models.SmallIntegerField(choices=[(0, '一般'), (1, '关注'), (2, '重要'), (3, '关键')], default=0, verbose_name='重要程度')),
                ('asset_service_type', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='业务类型')),
                ('asset_manager', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='系统管理员')),
                ('status', models.SmallIntegerField(choices=[(0, '在运'), (1, '停运')], default=0, verbose_name='设备状态')),
                ('company', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='公司')),
                ('department', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='部门')),
                ('owner', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='使用人')),
                ('cpu', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='硬盘')),
                ('cabinet', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='机柜号')),
                ('u_height', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='u高')),
                ('rail_num', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='导轨位置')),
                ('put_shelf_time', models.DateField(verbose_name='上线时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('comment', models.TextField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Area', verbose_name='区域')),
                ('asset_belong_system', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Application', verbose_name='所属系统')),
                ('manufacturer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Manufacturer', verbose_name='制造商')),
            ],
            options={
                'verbose_name_plural': '资产信息',
                'ordering': ['-create_time'],
            },
        ),
    ]
