# Generated by Django 2.2.5 on 2021-09-22 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='区域')),
                ('subnet', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='IP地址段')),
                ('describe', models.TextField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '所属区域',
            },
        ),
        migrations.CreateModel(
            name='PCManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='供应商')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='制造商')),
                ('contact', models.CharField(blank=True, max_length=16, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('describe', models.TextField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '供应商信息',
            },
        ),
        migrations.CreateModel(
            name='PCAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='主机名')),
                ('ip_add', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='IP地址')),
                ('mac_add', models.CharField(default='', max_length=48, verbose_name='MAC地址')),
                ('asset_use', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='用途')),
                ('asset_type', models.CharField(choices=[('pc', '桌面电脑'), ('laptop', '笔记本电脑'), ('printer', '网络打印机'), ('scanner', '扫描仪'), ('pad', '平板电脑'), ('phone', '手机'), ('smart_device', '智能终端'), ('other', '其它')], default='pc', max_length=64, verbose_name='资产类型')),
                ('company', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='公司')),
                ('department', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='部门')),
                ('owner', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='使用人')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('comment', models.TextField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_assets.PCArea', verbose_name='区域')),
                ('manufacturer', models.ForeignKey(blank=True, default='其它', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pc_assets.PCManufacturer', verbose_name='厂家')),
            ],
            options={
                'verbose_name_plural': '资产信息',
                'ordering': ['-create_time'],
            },
        ),
    ]
