# Generated by Django 2.2.5 on 2021-09-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True, max_length=64, null=True, verbose_name='起点')),
                ('destination', models.TextField(blank=True, max_length=64, null=True, verbose_name='终点')),
                ('describe', models.TextField(blank=True, max_length=64, null=True, verbose_name='用途')),
                ('manager', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '线缆信息管理',
            },
        ),
    ]
