# Generated by Django 2.2.5 on 2019-09-30 03:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='域名')),
                ('describe', models.CharField(blank=True, max_length=60, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '域名',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_record', models.CharField(max_length=64, verbose_name='主机记录')),
                ('record_type', models.SmallIntegerField(choices=[(0, 'A'), (1, 'CNAME'), (2, 'TXT'), (4, 'MX'), (5, 'MX')], default=0, verbose_name='记录类型')),
                ('record_value', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='记录值')),
                ('domain_describe', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('mod_date', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dns.Main', verbose_name='域名')),
            ],
            options={
                'verbose_name_plural': '解析记录',
            },
        ),
    ]
